"""Project Workspace (Surface #7): docs/API_CONTRACT_P9.md §7,
docs/PROJECT_AND_STACK.md §2, ADR 0006. The P8-T03 scope, absorbed into P9-T03.

**RBAC.** Surface `project_workspace`. Reads (workspace, files list,
download, activity) need READ: Portfolio Manager, Hub Planner, Engineer,
Executive Viewer, Admin, Super Admin. Every mutation needs WRITE: Portfolio
Manager, Hub Planner, Admin, Super Admin. Mutations are stage progress,
recalculate, file upload/edit and comment create/edit/delete.

**2026-09-30 (ADR 0012, P10-T02).** The role-level check above is necessary
but no longer sufficient by itself for gating mutations: every mutating
endpoint below also accepts a project-scoped `ProjectAccessGrant` via
`services.project_access.authorize_project_action` (never a duplicate of the
role check — that function composes with it). An Editor-level grant may
perform exactly three actions: stage-progress PATCH, file upload, and
comment post; every other mutation (file rename/recategorise, comment
edit/delete, recalculate) needs an Admin-level grant, same as a role that
already has Workspace WRITE. Read endpoints compose the same way one layer
down, in `services.workspace.get_scoped_project_or_404`: an active grant can
surface a project the caller's hub scope/own-assignment alone would not.

**Row scoping (P3-T03 pattern).** Every endpoint resolves the project
through `services.workspace.get_scoped_project_or_404`. Hub Planners see
their own hubs only; an Engineer sees their own assignments only. Out of
scope gives 404, exactly like a nonexistent project.

**Frozen projects (ruling 3).** Stage progress cannot be edited on a frozen
project: the stage PATCH returns 409 `PROJECT_FROZEN` ("Unfreeze on the Gantt
to record stage progress"). ADR 0006 already kept `frozen` and stage progress
apart; this enforces it.

**Progress edits never solve (ADR 0006).** `PATCH …/stages/{step_id}` sets
`schedule_stale` and writes an audit row. The row records the blocked
reason's length, not its text. A transition *into* Blocked also sends a
`stage_blocked` notification to the Hub Planners of the project's hub and to
Portfolio Managers (`services.notifications.
generate_stage_blocked_notifications`). The message holds project, hub,
stage and reason only; no person's name (OQ#8). `POST …/recalculate` is the only
thing that schedules. It dispatches the **greedy** scheduler through the
P3-T06 Celery lifecycle (`workers.schedule_tasks.run_greedy_schedule`, with
`activate=True`). CP-SAT is not used here: docs/OPEN_QUESTIONS.md #10 blocks
exposing CP-SAT through a user-facing action until the client answers
(P9-T03 follow-up). The admin-only `POST /schedule-runs/cp-sat-dispatch` is
unchanged. The completed run becomes the active schedule, clears the stale
flags, and writes the "Schedule recalculated — finish moved week X → week Y"
event.
Every recalculation creates a new `ScheduleRun` row (I14). A recalculation
is refused with 409 `RUN_IN_PROGRESS` while another solver run started
recently is still queued or running, so two activations cannot race.

**Files (MinIO).** The extension must be on the allowlist, the bytes must
match it (`services.file_sniff`), and the size is capped at 50 MB (413
`FILE_TOO_LARGE`). The object key is generated by the server
(`projects/<project_id>/files/<uuid4 hex>`) and never derived from the
display name or the uploaded filename. Re-uploading an existing display name
creates version N+1. Downloads stream from MinIO with a sanitised
`Content-Disposition` and `X-Content-Type-Options: nosniff`. The reverse
proxy should also cap request bodies (for example `client_max_body_size`):
the 50 MB check here runs after the multipart body has been received.

**Comments.** Markdown is stored and returned as written (`body_md`, at most
10 000 characters, 422 above). The server no longer renders HTML (P9-R02,
security S-02: re-rendering every comment on every read could stall the
event loop, and nothing consumed it); the frontend renders `body_md` with its
own React-elements-only renderer. Comment creation is rate-limited per user
(`COMMENT_RATE_LIMIT`, in-process token bucket, 429 `RATE_LIMITED` with
`Retry-After`; see `services.rate_limit` for its limits). Only the author may edit, and only
within 15 minutes (403 `EDIT_LOCKED`; 403 `NOT_AUTHOR` for anyone else).
Deletion is soft (`soft_deleted_at`; the DB trigger forbids a hard delete),
by the author or an Admin / Super Admin. Audit rows for comments record
ids and lengths, never the text: comments may contain personal data, and
the audit log is immutable.

**OQ#8.** Person names are withheld exactly as the P3-T09 pattern decides.
See `schemas/workspace.py`. `@mentions` are not resolved and
`mentioned_user_ids` is always empty until the DPO signs off. A mention
notification would also need a new `NotificationReason`, which is deferred
with it.
"""

from __future__ import annotations

import math
import re
import uuid
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from typing import Any
from urllib.parse import quote

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status
from fastapi.responses import StreamingResponse
from minio.error import S3Error
from sqlalchemy import func, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.concurrency import run_in_threadpool

from api.db import get_db
from api.deps import get_current_principal, require_permission
from api.errors import HTTP_413, HTTP_422, CodedHTTPException, field_error
from core.celery_config import get_celery_settings
from core.minio_config import ensure_bucket, get_minio_client, get_minio_settings
from core.principal import Principal
from core.rbac import Action, Surface
from models.audit import AuditLogEntry
from models.enums import (
    ProjectFileCategory,
    RoleName,
    ScheduleRunStatus,
    SolverType,
    WorkflowStepStatus,
)
from models.project import Project
from models.schedule import ScheduleRun
from models.workflow import ProjectWorkflowStep, WorkflowStepTemplate
from models.workspace import ProjectComment, ProjectFile
from schemas.workspace import (
    ActivityItem,
    CommentCreateRequest,
    CommentRead,
    CommentUpdateRequest,
    FileRead,
    FileUpdateRequest,
    RecalculateResponse,
    StageUpdateRequest,
    WorkspaceRead,
)
from services.file_sniff import EXTENSION_FOR_CONTENT_TYPE, UploadRejected, extension_of, sniff
from services.notifications import generate_stage_blocked_notifications
from services.project_access import authorize_project_action
from services.project_steps import WorkflowChangeWithProgress, sync_project_steps
from services.rate_limit import TokenBucketLimiter
from services.schedule_persistence import create_queued_schedule_run
from services.schedule_stale import mark_projects_stale
from services.workspace import (
    ACTIVITY_DEFAULT_LIMIT,
    ACTIVITY_MAX_LIMIT,
    COMMENT_EDIT_WINDOW,
    build_workspace,
    comment_read,
    file_read,
    get_scoped_project_or_404,
    list_activity,
    merge_stage_update,
)
from workers.progress import publish_progress
from workers.schedule_tasks import run_greedy_schedule

router = APIRouter(prefix="/projects", tags=["project-workspace"])

_read = require_permission(Surface.PROJECT_WORKSPACE, Action.READ)
#: 2026-09-30 (ADR 0012, P10-T02): every mutation below composes this
#: surface-level role check with `services.project_access.
#: authorize_project_action` rather than hard-depending on a hand-rolled
#: `require_permission(..., Action.WRITE)` dependency — a caller whose only
#: basis for access is a project-scoped Editor/Admin `ProjectAccessGrant`
#: (no role-level Workspace WRITE at all) must still be authorized for the
#: actions their grant covers. See each endpoint's own `authorize_project_action`
#: call for its `min_grant_role`.

MAX_UPLOAD_BYTES = 50 * 1024 * 1024
#: Security S-02 (P9-R02): per user, a burst of 10 comments, then one every
#: 6 seconds (10 per minute sustained). Per API process; see
#: `services.rate_limit` for the documented limitation.
COMMENT_RATE_LIMIT = TokenBucketLimiter(capacity=10, refill_per_second=1 / 6)
_CHUNK = 1024 * 1024
_ADMIN_ROLES = frozenset({RoleName.ADMIN, RoleName.SUPER_ADMIN})


async def _project_or_404(db: AsyncSession, project_id: uuid.UUID, principal: Principal) -> Project:
    project = await get_scoped_project_or_404(db, project_id, principal)
    if project is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found")
    return project


# --- Read model -----------------------------------------------------------------------


@router.get("/{project_id}/workspace", response_model=WorkspaceRead)
async def get_workspace(
    project_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(_read),
) -> WorkspaceRead:
    project = await _project_or_404(db, project_id, current_user)
    return await build_workspace(db, project, current_user)


@router.get("/{project_id}/activity", response_model=list[ActivityItem])
async def get_activity(
    project_id: uuid.UUID,
    before: datetime | None = Query(default=None),
    limit: int = Query(default=ACTIVITY_DEFAULT_LIMIT, ge=1, le=ACTIVITY_MAX_LIMIT),
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(_read),
) -> list[Any]:
    """Older activity: items strictly before `before`, newest first. Pass the
    last item's timestamp as the next `before`.
    """

    project = await _project_or_404(db, project_id, current_user)
    return await list_activity(db, project, current_user, before=before, limit=limit)


# --- Stage progress (DOMAIN_RULES "Per-stage progress fields") ------------------------


@router.patch("/{project_id}/stages/{step_id}", response_model=WorkspaceRead)
async def patch_stage(
    project_id: uuid.UUID,
    step_id: str,
    body: StageUpdateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> WorkspaceRead:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: stage-progress PATCH is one of the three actions an
    # Editor-level `ProjectAccessGrant` may perform (the other two are file
    # upload and comment post) — never a Registration charter field,
    # freeze/unfreeze, or precedence edit.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="editor",
    )
    if project.frozen:
        raise CodedHTTPException(
            status.HTTP_409_CONFLICT,
            "PROJECT_FROZEN",
            "This project is frozen. Unfreeze on the Gantt to record stage progress.",
        )
    try:
        await sync_project_steps(db, project, project.hub.is_oem)
    except WorkflowChangeWithProgress as exc:  # pragma: no cover - needs corrupt data
        raise CodedHTTPException(
            HTTP_422, "WORKFLOW_CHANGE_WITH_PROGRESS", str(exc)
        ) from exc
    row = (
        await db.execute(
            select(ProjectWorkflowStep).where(
                ProjectWorkflowStep.project_id == project.id,
                ProjectWorkflowStep.step_template_id == step_id,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Stage {step_id!r} is not a stage of this project's workflow",
        )
    if row.duration_weeks == 0:
        raise CodedHTTPException(
            HTTP_422,
            "STAGE_SKIPPED",
            f"Stage {step_id!r} is skipped for this project (0 weeks) and has no progress "
            "of its own.",
        )

    explicit = body.model_dump(exclude_unset=True)
    if "status" in explicit and explicit["status"] is None:
        raise CodedHTTPException(
            HTTP_422,
            "STAGE_INCONSISTENT",
            [field_error("status", "may not be null")],
        )
    if "percent_complete" in explicit and explicit["percent_complete"] is None:
        raise CodedHTTPException(
            HTTP_422,
            "STAGE_INCONSISTENT",
            [field_error("percent_complete", "may not be null")],
        )
    merged, errors = merge_stage_update(row, explicit)
    if errors:
        raise CodedHTTPException(
            HTTP_422,
            "STAGE_INCONSISTENT",
            [field_error(name, msg) for name, msg in errors],
        )

    before_state = _stage_state(project, row)
    was_blocked = row.status == WorkflowStepStatus.BLOCKED
    for name, value in merged.items():
        setattr(row, name, value)
    await db.flush()
    await mark_projects_stale(db, [project.id])
    if row.status == WorkflowStepStatus.BLOCKED and not was_blocked:
        # P9-T03 follow-up: a Blocked stage "surfaces on Notifications".
        step_name = (
            await db.execute(
                select(WorkflowStepTemplate.name).where(WorkflowStepTemplate.id == step_id)
            )
        ).scalar_one()
        await generate_stage_blocked_notifications(
            db,
            project=project,
            hub_name=project.hub.name.value,
            step_id=step_id,
            step_name=step_name,
            reason=row.blocked_reason or "",
            actor_user_id=current_user.user_id,
        )
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project_stage.update",
            entity_type="ProjectWorkflowStep",
            entity_id=str(row.id),
            hub_id=project.hub_id,
            before_state=before_state,
            after_state=_stage_state(project, row),
        )
    )
    await db.commit()
    await db.refresh(project)
    return await build_workspace(db, project, current_user)


def _stage_state(project: Project, row: ProjectWorkflowStep) -> dict[str, Any]:
    return {
        "project_id": str(project.id),
        "step_id": row.step_template_id,
        "status": row.status.value,
        "percent_complete": row.percent_complete,
        "actual_start_week": row.actual_start_week,
        "actual_end_week": row.actual_end_week,
        "remaining_weeks_override": row.remaining_weeks_override,
        # The reason is free text and may contain personal data; the audit
        # log is immutable, so only its length is recorded (like comments).
        "blocked_reason_length": len(row.blocked_reason) if row.blocked_reason else 0,
    }


# --- Recalculate (ADR 0006, I14) ------------------------------------------------------


@router.post(
    "/{project_id}/recalculate",
    response_model=RecalculateResponse,
    status_code=status.HTTP_202_ACCEPTED,
)
async def recalculate(
    project_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> RecalculateResponse:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: recalculate is NOT one of the Editor grant's three permitted
    # actions, so it needs project-scoped Admin (or the unchanged role-level
    # WRITE this endpoint already required).
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="admin",
    )

    window = timedelta(seconds=get_celery_settings().task_time_limit_seconds + 120)
    in_flight = (
        await db.execute(
            select(ScheduleRun.id)
            .where(
                ScheduleRun.status.in_([ScheduleRunStatus.QUEUED, ScheduleRunStatus.RUNNING]),
                ScheduleRun.created_at > datetime.now(UTC) - window,
            )
            .limit(1)
        )
    ).scalar_one_or_none()
    if in_flight is not None:
        raise CodedHTTPException(
            status.HTTP_409_CONFLICT,
            "RUN_IN_PROGRESS",
            f"A schedule run ({in_flight}) is already queued or running. Follow its progress "
            "and try again when it finishes.",
        )

    # GREEDY, not CP-SAT: docs/OPEN_QUESTIONS.md #10 blocks exposing CP-SAT
    # through a user-facing action until the client answers.
    run = await create_queued_schedule_run(
        db,
        solver_type=SolverType.GREEDY,
        trigger_reason="workspace_recalc",
        triggered_by_user_id=current_user.user_id,
    )
    async_result = run_greedy_schedule.delay(
        str(run.id),
        triggered_by_user_id=str(current_user.user_id),
        activate=True,
        recalc_project_id=str(project.id),
    )
    run.celery_task_id = async_result.id
    db.add(run)
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project.recalculate_requested",
            entity_type="Project",
            entity_id=str(project.id),
            hub_id=project.hub_id,
            before_state=None,
            after_state={
                "project_id": str(project.id),
                "schedule_run_id": str(run.id),
                "schedule_run_version": run.version,
                "celery_task_id": run.celery_task_id,
            },
        )
    )
    await db.commit()
    publish_progress(str(run.id), status="queued")
    return RecalculateResponse(schedule_run_id=run.id, task_id=str(async_result.id))


# --- Files (MinIO) --------------------------------------------------------------------


def _read_capped(upload: UploadFile) -> int:
    """Count the upload's bytes, stopping as soon as it passes the cap.
    Leaves the file at position 0.
    """

    size = 0
    upload.file.seek(0)
    while chunk := upload.file.read(_CHUNK):
        size += len(chunk)
        if size > MAX_UPLOAD_BYTES:
            break
    upload.file.seek(0)
    return size


def _content_disposition(display_name: str, content_type: str) -> str:
    """`attachment` with an ASCII-only `filename` fallback (quotes, control
    characters and path separators stripped) and an RFC 5987 `filename*`.
    The display name never reaches the header unescaped.
    """

    ext = EXTENSION_FOR_CONTENT_TYPE.get(content_type, "bin")
    name = display_name.strip() or "file"
    if not name.lower().endswith(f".{ext}"):
        name = f"{name}.{ext}"
    ascii_name = re.sub(r"[^A-Za-z0-9._ -]", "_", name)[:200] or f"file.{ext}"
    return f"attachment; filename=\"{ascii_name}\"; filename*=UTF-8''{quote(name, safe='')}"


@router.get("/{project_id}/files", response_model=list[FileRead])
async def list_files(
    project_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(_read),
) -> list[FileRead]:
    project = await _project_or_404(db, project_id, current_user)
    files = (
        (
            await db.execute(
                select(ProjectFile)
                .where(ProjectFile.project_id == project.id)
                .order_by(ProjectFile.display_name, ProjectFile.version.desc())
            )
        )
        .scalars()
        .all()
    )
    return [file_read(f, current_user) for f in files]


@router.post(
    "/{project_id}/files", response_model=FileRead, status_code=status.HTTP_201_CREATED
)
async def upload_file(
    project_id: uuid.UUID,
    file: UploadFile = File(...),
    display_name: str = Form(..., min_length=1, max_length=255),
    category: ProjectFileCategory = Form(...),
    description: str | None = Form(default=None, max_length=2000),
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> FileRead:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: file upload is one of the Editor grant's three permitted
    # actions.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="editor",
    )
    display = display_name.strip()
    if not display:
        raise CodedHTTPException(
            HTTP_422,
            "BAD_DISPLAY_NAME",
            [field_error("display_name", "must not be blank")],
        )

    size = await run_in_threadpool(_read_capped, file)
    if size > MAX_UPLOAD_BYTES:
        raise CodedHTTPException(
            HTTP_413, "FILE_TOO_LARGE", "Files are limited to 50 MB."
        )
    if size == 0:
        raise CodedHTTPException(
            HTTP_422, "EMPTY_FILE", "The file is empty."
        )
    try:
        ext = extension_of(file.filename)
        content_type = await run_in_threadpool(sniff, ext, file.file)
    except UploadRejected as exc:
        raise CodedHTTPException(
            status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, "UNSUPPORTED_FILE_TYPE", str(exc)
        ) from exc

    latest = (
        await db.execute(
            select(func.max(ProjectFile.version)).where(
                ProjectFile.project_id == project.id, ProjectFile.display_name == display
            )
        )
    ).scalar_one_or_none()
    version = (latest or 0) + 1
    object_key = f"projects/{project.id}/files/{uuid.uuid4().hex}"

    client = get_minio_client()
    bucket = get_minio_settings().attachments_bucket
    try:
        await run_in_threadpool(ensure_bucket, client, bucket)
        await run_in_threadpool(
            client.put_object, bucket, object_key, file.file, size, content_type=content_type
        )
    except S3Error as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY, detail="Object storage rejected the upload"
        ) from exc

    record = ProjectFile(
        project_id=project.id,
        display_name=display,
        category=category,
        description=description,
        uploaded_by_user_id=current_user.user_id,
        size_bytes=size,
        content_type=content_type,
        version=version,
        minio_object_key=object_key,
    )
    db.add(record)
    try:
        await db.flush()
        db.add(
            AuditLogEntry(
                actor_user_id=current_user.user_id,
                action="project_file.upload",
                entity_type="ProjectFile",
                entity_id=str(record.id),
                hub_id=project.hub_id,
                before_state=None,
                after_state=_file_state(project, record),
            )
        )
        await db.commit()
    except IntegrityError as exc:
        await db.rollback()
        await run_in_threadpool(_remove_object_quietly, bucket, object_key)
        raise CodedHTTPException(
            status.HTTP_409_CONFLICT,
            "VERSION_CONFLICT",
            "Another upload of this display name finished first. Retry the upload.",
        ) from exc
    await db.refresh(record)
    return file_read(record, current_user)


def _remove_object_quietly(bucket: str, object_key: str) -> None:
    try:
        get_minio_client().remove_object(bucket, object_key)
    except S3Error:  # pragma: no cover - best effort cleanup of an orphan
        pass


def _file_state(project: Project, f: ProjectFile) -> dict[str, Any]:
    return {
        "project_id": str(project.id),
        "display_name": f.display_name,
        "version": f.version,
        "category": f.category.value,
        "size_bytes": f.size_bytes,
        "content_type": f.content_type,
        "description_length": len(f.description or ""),
    }


async def _file_or_404(db: AsyncSession, project: Project, file_id: uuid.UUID) -> ProjectFile:
    record = (
        await db.execute(
            select(ProjectFile).where(
                ProjectFile.id == file_id, ProjectFile.project_id == project.id
            )
        )
    ).scalar_one_or_none()
    if record is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File not found")
    return record


@router.get("/{project_id}/files/{file_id}/download")
async def download_file(
    project_id: uuid.UUID,
    file_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(_read),
) -> StreamingResponse:
    project = await _project_or_404(db, project_id, current_user)
    record = await _file_or_404(db, project, file_id)
    client = get_minio_client()
    bucket = get_minio_settings().attachments_bucket
    try:
        obj = await run_in_threadpool(client.get_object, bucket, record.minio_object_key)
    except S3Error as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to retrieve the file from object storage",
        ) from exc

    def _iter() -> Iterator[bytes]:
        try:
            yield from obj.stream(64 * 1024)
        finally:
            obj.close()
            obj.release_conn()

    return StreamingResponse(
        _iter(),
        media_type=record.content_type,
        headers={
            "Content-Disposition": _content_disposition(record.display_name, record.content_type),
            "Content-Length": str(record.size_bytes),
            "X-Content-Type-Options": "nosniff",
            "Cache-Control": "private, no-store",
        },
    )


@router.patch("/{project_id}/files/{file_id}", response_model=FileRead)
async def update_file(
    project_id: uuid.UUID,
    file_id: uuid.UUID,
    body: FileUpdateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> FileRead:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: renaming/recategorising a file is NOT one of the Editor
    # grant's three permitted actions (only the upload itself is) — needs
    # project-scoped Admin.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="admin",
    )
    record = await _file_or_404(db, project, file_id)
    updates = body.model_dump(exclude_unset=True)
    for key in ("display_name", "category"):
        if key in updates and updates[key] is None:
            raise CodedHTTPException(
                HTTP_422, "NULL_NOT_ALLOWED", f"{key} may not be null"
            )
    before_state = _file_state(project, record)

    new_name = updates.get("display_name")
    if new_name is not None:
        new_name = new_name.strip()
        if not new_name:
            raise CodedHTTPException(
                HTTP_422,
                "BAD_DISPLAY_NAME",
                [field_error("display_name", "must not be blank")],
            )
    if new_name is not None and new_name != record.display_name:
        taken = (
            await db.execute(
                select(ProjectFile.id)
                .where(ProjectFile.project_id == project.id, ProjectFile.display_name == new_name)
                .limit(1)
            )
        ).first()
        if taken is not None:
            raise CodedHTTPException(
                status.HTTP_409_CONFLICT,
                "DISPLAY_NAME_TAKEN",
                "Another document on this project already uses that display name.",
            )
        # The display name identifies the document, so every version moves.
        await db.execute(
            update(ProjectFile)
            .where(
                ProjectFile.project_id == project.id,
                ProjectFile.display_name == record.display_name,
            )
            .values(display_name=new_name)
            .execution_options(synchronize_session=False)
        )
        record.display_name = new_name
    if "category" in updates:
        record.category = updates["category"]
    if "description" in updates:
        record.description = updates["description"]
    await db.flush()
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project_file.update",
            entity_type="ProjectFile",
            entity_id=str(record.id),
            hub_id=project.hub_id,
            before_state=before_state,
            after_state=_file_state(project, record),
        )
    )
    await db.commit()
    await db.refresh(record)
    return file_read(record, current_user)


# --- Comments -------------------------------------------------------------------------


def _comment_state(project: Project, c: ProjectComment) -> dict[str, Any]:
    return {
        "project_id": str(project.id),
        "comment_id": str(c.id),
        "body_length": len(c.body_md),
        "deleted": c.soft_deleted_at is not None,
    }


async def _comment_or_404(
    db: AsyncSession, project: Project, comment_id: uuid.UUID
) -> ProjectComment:
    comment = (
        await db.execute(
            select(ProjectComment).where(
                ProjectComment.id == comment_id,
                ProjectComment.project_id == project.id,
                ProjectComment.soft_deleted_at.is_(None),
            )
        )
    ).scalar_one_or_none()
    if comment is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Comment not found")
    return comment


@router.post(
    "/{project_id}/comments", response_model=CommentRead, status_code=status.HTTP_201_CREATED
)
async def create_comment(
    project_id: uuid.UUID,
    body: CommentCreateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> CommentRead:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: comment post is one of the Editor grant's three permitted
    # actions.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="editor",
    )
    allowed, retry_after = COMMENT_RATE_LIMIT.allow(str(current_user.user_id))
    if not allowed:
        raise CodedHTTPException(
            status.HTTP_429_TOO_MANY_REQUESTS,
            "RATE_LIMITED",
            "Too many comments. Please wait a moment before posting again.",
            headers={"Retry-After": str(max(1, math.ceil(retry_after)))},
        )
    comment = ProjectComment(
        project_id=project.id,
        body_md=body.body_md,
        author_user_id=current_user.user_id,
        mentioned_user_ids=[],
    )
    db.add(comment)
    await db.flush()
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project_comment.create",
            entity_type="ProjectComment",
            entity_id=str(comment.id),
            hub_id=project.hub_id,
            before_state=None,
            after_state=_comment_state(project, comment),
        )
    )
    await db.commit()
    await db.refresh(comment)
    return comment_read(comment, current_user, datetime.now(UTC))


@router.patch("/{project_id}/comments/{comment_id}", response_model=CommentRead)
async def edit_comment(
    project_id: uuid.UUID,
    comment_id: uuid.UUID,
    body: CommentUpdateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> CommentRead:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: editing a comment (as opposed to posting a new one) is NOT
    # one of the Editor grant's three permitted actions — needs
    # project-scoped Admin. The author-only/15-minute rules below are
    # unchanged and still apply on top of this.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="admin",
    )
    comment = await _comment_or_404(db, project, comment_id)
    if comment.author_user_id != current_user.user_id:
        raise CodedHTTPException(
            status.HTTP_403_FORBIDDEN, "NOT_AUTHOR", "Only the author may edit a comment."
        )
    now = datetime.now(UTC)
    if now >= comment.created_at + COMMENT_EDIT_WINDOW:
        raise CodedHTTPException(
            status.HTTP_403_FORBIDDEN,
            "EDIT_LOCKED",
            "Comments can only be edited within 15 minutes of posting.",
        )
    before_state = _comment_state(project, comment)
    comment.body_md = body.body_md
    comment.edited_at = now
    await db.flush()
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project_comment.update",
            entity_type="ProjectComment",
            entity_id=str(comment.id),
            hub_id=project.hub_id,
            before_state=before_state,
            after_state=_comment_state(project, comment),
        )
    )
    await db.commit()
    await db.refresh(comment)
    return comment_read(comment, current_user, now)


@router.delete(
    "/{project_id}/comments/{comment_id}", status_code=status.HTTP_204_NO_CONTENT
)
async def delete_comment(
    project_id: uuid.UUID,
    comment_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: Principal = Depends(get_current_principal),
) -> None:
    project = await _project_or_404(db, project_id, current_user)
    # ADR 0012: deleting a comment is NOT one of the Editor grant's three
    # permitted actions — needs project-scoped Admin. The author-or-Admin
    # rule below is unchanged and still applies on top of this.
    await authorize_project_action(
        db, current_user, project,
        surface=Surface.PROJECT_WORKSPACE, action=Action.WRITE, min_grant_role="admin",
    )
    comment = await _comment_or_404(db, project, comment_id)
    is_admin = bool(current_user.roles & _ADMIN_ROLES)
    if comment.author_user_id != current_user.user_id and not is_admin:
        raise CodedHTTPException(
            status.HTTP_403_FORBIDDEN,
            "NOT_AUTHOR",
            "Only the author or an Admin may delete a comment.",
        )
    before_state = _comment_state(project, comment)
    comment.soft_deleted_at = datetime.now(UTC)
    await db.flush()
    db.add(
        AuditLogEntry(
            actor_user_id=current_user.user_id,
            action="project_comment.delete",
            entity_type="ProjectComment",
            entity_id=str(comment.id),
            hub_id=project.hub_id,
            before_state=before_state,
            after_state=_comment_state(project, comment),
        )
    )
    await db.commit()
