import type { WorkspaceResponse, WorkspaceStage } from './api/types';

const NAMES: [string, string, WorkspaceStage['kind']][] = [
  ['A', 'Marketing Brief', 'design'],
  ['B', 'Feasibility Study (Conceptual Design)', 'design'],
  ['C', 'Business Case Approval', 'elapsed'],
  ['D', 'Final Technical Brief & Project Kick-off', 'design'],
  ['E', 'Design Detailing', 'design'],
  ['F', 'Proof of Concept', 'lab'],
  ['G', 'Online CAPEX Approval', 'elapsed'],
  ['H', 'Certification Testing & Compliance', 'lab'],
  ['I', 'TF-1', 'design'],
  ['J', 'Pre-Production (Pr. Pr)', 'design'],
  ['K', 'TF-2', 'design'],
  ['L', 'Pilot', 'elapsed'],
  ['M', 'TF-3', 'design'],
  ['N', 'Commercialization', 'elapsed'],
];

export function stage(i: number, over: Partial<WorkspaceStage> = {}): WorkspaceStage {
  const [letter, name, kind] = NAMES[i]!;
  return {
    step_id: `PDD-${letter}`,
    code: letter,
    name,
    kind,
    sequence_order: i + 1,
    predecessor_ids: i === 0 ? [] : [`PDD-${NAMES[i - 1]![0]}`],
    duration_weeks: 2,
    skipped: false,
    planned_start_week: 31 + i * 2,
    planned_end_week: 32 + i * 2,
    actual_start_week: null,
    actual_end_week: null,
    status: 'Not Started',
    percent_complete: 0,
    remaining_weeks: 2,
    remaining_weeks_override: null,
    blocked_reason: null,
    assigned_engineer_name: null,
    assigned_chamber_code: kind === 'lab' ? 'IN-CH-2' : null,
    overrun_weeks: null,
    ...over,
  };
}

export function workspaceFixture(over: Partial<WorkspaceResponse> = {}): WorkspaceResponse {
  return {
    project: {
      id: 'p-1',
      name: 'Cooler Alpha',
      external_code: 'RPD-0042',
      hub_id: 'hub-in',
      hub: 'PD-India',
      leader_engineer_id: 'eng-1',
      leader_engineer_name: null,
      category: 'A',
      type: 'NM',
      priority: 'P2',
      status: 'In Development',
      frozen: false,
      actual_start_week: 20,
      delay_weeks: 0,
      reg_year: 2026,
      carry_over: false,
      comments: null,
      customer_name: 'Acme Retail',
      tcogs_eur: 1000,
      selling_price_eur: 1500,
      gross_margin_pct: 33.3,
      capex_keur: 45,
      rm_savings_keur: 12,
      target_end_week: 48,
      certification_testing_required: true,
      estimated_design_weeks: 18,
      estimated_lab_weeks: 10,
      schedule_stale: false,
      workflow_id: 'PDD',
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-09-27T09:00:00Z',
    },
    health: 'on_track',
    schedule: {
      has_active_run: true,
      run_version: 7,
      expected_end_week: 48,
      projected_end_week: 50,
      unconstrained_end_week: 46,
      slip_weeks: 2,
      within_year: true,
      left_out: false,
      schedule_stale: false,
    },
    progress_pct: 37,
    stages: NAMES.map((_, i) =>
      i === 0
        ? stage(0, { status: 'Done', percent_complete: 100, actual_start_week: 20, actual_end_week: 21, remaining_weeks: 0 })
        : i === 1
          ? stage(1, { status: 'In Progress', percent_complete: 50, actual_start_week: 22, overrun_weeks: 1 })
          : i === 2
            ? stage(2, { skipped: true, duration_weeks: 0 })
            : stage(i),
    ),
    priority_score: {
      strategic_project: 5,
      new_customer: 4,
      new_options: 3,
      regulatory_compliance: 2,
      quality_improvements: 3,
      rm_savings: 4,
      total_rm_savings: 3,
      gross_margins: 3,
      profitability: 4,
      annual_volume: 3,
      three_year_volume: 3,
      new_models: 2,
      capex_investment: 4,
      hard_gates: [],
      weighted_score: 980,
      normalized_pct: 70,
      suggested_band: 'P1',
    },
    files: [
      {
        id: 'f-1',
        display_name: 'Certification report',
        category: 'Certification',
        description: 'EN 60335',
        version: 2,
        size_bytes: 204800,
        content_type: 'application/pdf',
        uploaded_by_name: null,
        created_at: '2026-09-20T09:00:00Z',
      },
      {
        id: 'f-0',
        display_name: 'Certification report',
        category: 'Certification',
        description: 'First draft',
        version: 1,
        size_bytes: 102400,
        content_type: 'application/pdf',
        uploaded_by_name: 'Sam Super',
        created_at: '2026-09-10T09:00:00Z',
      },
    ],
    activity: [
      {
        kind: 'comment',
        comment: {
          id: 'c-1',
          body_md: 'Supplier **confirmed** the compressor. cc @Nikos\n\n<script>alert(1)</script>',
          author_name: 'Sam Super',
          author_user_id: 'user-super',
          created_at: new Date().toISOString(),
          edited_at: null,
          can_edit: true,
          mentioned_user_ids: [],
        },
      },
      {
        kind: 'event',
        id: 'e-1',
        occurred_at: '2026-09-26T08:00:00Z',
        actor_name: null,
        summary: 'Schedule recalculated — finish moved week 49 → week 50',
        audit_entry_id: 'a-1',
      },
      {
        kind: 'comment',
        comment: {
          id: 'c-2',
          body_md: 'Old note from another planner.',
          author_name: null,
          author_user_id: 'user-other',
          created_at: '2026-09-01T08:00:00Z',
          edited_at: null,
          can_edit: false,
          mentioned_user_ids: [],
        },
      },
    ],
    ...over,
  };
}
