"""initial schema

Revision ID: 419f196fd00b
Revises: 
Create Date: 2026-08-29 22:23:43.546218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import models.types

# revision identifiers, used by Alembic.
revision: str = '419f196fd00b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- Hand-written additions (not producible by autogenerate) -------------
#
# 1. Partial unique indexes enforcing "at most one active row" on
#    `schedule_runs.is_active` and `priority_application_runs.is_active`.
#    This is the DB-level mechanism behind Invariant I9 (docs/DOMAIN_RULES.md:
#    "within_year count on the Dashboard equals the count ... in the current
#    schedule run. No independent calculation anywhere") — every read surface
#    that needs "the" active schedule/priority run can rely on there being at
#    most one, enforced by Postgres itself rather than by application
#    discipline alone. A plain SQLAlchemy `UniqueConstraint`/`unique=True`
#    column flag cannot express "unique only among TRUE rows" — Postgres
#    partial indexes are DDL-only, hence written by hand here (see
#    docs/MEMORY.md P1-T01 entry, Decision #6).
#
# 2. Append-only enforcement on `audit_log_entries` via a trigger that
#    rejects UPDATE and DELETE outright. Chosen over a REVOKE-based approach
#    because a trigger is enforced regardless of which DB role/connection
#    performs the write (the API's normal runtime role, a future ad-hoc
#    admin/migration script, a different service account, etc.) — REVOKE
#    only protects against roles it is explicitly applied to and is easy to
#    silently bypass by connecting as a more privileged role (e.g. the
#    migration-owner role, which must retain DDL/DML rights to run future
#    migrations against this table's schema in the first place). CLAUDE.md's
#    non-negotiable is "immutable append-only audit log"; this is that
#    guarantee enforced at the database layer, per backend/models/audit.py's
#    docstring, which explicitly defers this to the P1-T02 migration.
_SCHEDULE_RUNS_ACTIVE_IDX = "ux_schedule_runs_one_active"
_PRIORITY_RUNS_ACTIVE_IDX = "ux_priority_application_runs_one_active"
_AUDIT_TRIGGER_FN = "audit_log_entries_reject_mutation"
_AUDIT_TRIGGER_NAME = "trg_audit_log_entries_append_only"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('lab_region', sa.Enum('Greece', 'India', 'Romania', name='lab_region'), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('platforms', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weeks_per_chamber', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('allowed_stages', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chambers')),
    sa.UniqueConstraint('code', name=op.f('uq_chambers_code'))
    )
    op.create_table('hubs',
    sa.Column('name', sa.Enum('R&D-Greece', 'R&D-India', 'PD-India', 'PD-Romania', 'OEM-HCK', 'OEM-Seltek', name='hub_name'), nullable=False),
    sa.Column('lab_region', sa.Enum('Greece', 'India', 'Romania', name='lab_region'), nullable=False),
    sa.Column('is_oem', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hubs')),
    sa.UniqueConstraint('name', name=op.f('uq_hubs_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('hub_scope_all', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('oidc_subject', name=op.f('uq_users_oidc_subject'))
    )
    op.create_table('workflow_step_templates',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('design', 'lab', name='workflow_step_kind'), nullable=False),
    sa.Column('base_weeks', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_order BETWEEN 1 AND 14', name=op.f('ck_workflow_step_templates_sequence_order_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step_templates')),
    sa.UniqueConstraint('sequence_order', name=op.f('uq_workflow_step_templates_sequence_order'))
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('hub_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_entries_actor_user_id_users')),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_audit_log_entries_hub_id_hubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries'))
    )
    op.create_table('currency_rates',
    sa.Column('currency_code', sa.Enum('EUR', 'USD', 'INR', name='currency_code'), nullable=False),
    sa.Column('rate_to_eur', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_currency_rates_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_rates')),
    sa.UniqueConstraint('currency_code', name=op.f('uq_currency_rates_currency_code'))
    )
    op.create_table('engineers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hub_id', sa.Uuid(), nullable=False),
    sa.Column('fte', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('allowed_categories', sa.ARRAY(sa.Enum('A+', 'A', 'B', 'C', 'OEM', name='engineer_allowed_category')), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_engineers_hub_id_hubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_engineers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engineers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_engineers_user_id'))
    )
    op.create_table('priority_application_runs',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applied_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], name=op.f('fk_priority_application_runs_applied_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_application_runs')),
    sa.UniqueConstraint('version', name=op.f('uq_priority_application_runs_version'))
    )
    op.create_table('schedule_runs',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('solver_type', sa.Enum('greedy', 'cp_sat', name='solver_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='schedule_run_status'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_schedule_runs_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_runs')),
    sa.UniqueConstraint('version', name=op.f('uq_schedule_runs_version'))
    )
    op.create_table('user_hub_scopes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hub_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_user_hub_scopes_hub_id_hubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_hub_scopes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'hub_id', name=op.f('pk_user_hub_scopes'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=True),
    sa.Column('hub_id', sa.Uuid(), nullable=False),
    sa.Column('leader_engineer_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('A+', 'A', 'B', 'C', name='project_category'), nullable=True),
    sa.Column('type', sa.Enum('NM', 'CO', 'RC', 'NO', 'IMP', name='project_type'), nullable=True),
    sa.Column('status', sa.Enum('In Buyoff', 'Under Industrialization', 'In Development', 'In Queue', 'Commercialized', 'On Hold', 'Draft', name='project_status'), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', 'Q', name='project_priority'), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('actual_start_week', sa.Integer(), nullable=True),
    sa.Column('delay_weeks', sa.Integer(), nullable=False),
    sa.Column('reg_year', sa.Integer(), nullable=True),
    sa.Column('carry_over', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('customer_name', models.types.EncryptedString(), nullable=True),
    sa.Column('tcogs_eur', models.types.EncryptedNumeric(), nullable=True),
    sa.Column('selling_price_eur', models.types.EncryptedNumeric(), nullable=True),
    sa.Column('gross_margin_pct', models.types.EncryptedNumeric(), nullable=True),
    sa.Column('capex_keur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rm_savings_keur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_projects_hub_id_hubs')),
    sa.ForeignKeyConstraint(['leader_engineer_id'], ['engineers.id'], name=op.f('fk_projects_leader_engineer_id_engineers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('external_code', name=op.f('uq_projects_external_code'))
    )
    op.create_table('priority_application_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('priority_application_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('normalized_pct', sa.Integer(), nullable=False),
    sa.Column('suggested_band', sa.Enum('P1', 'P2', 'P3', 'P4', 'Q', name='project_priority'), nullable=False),
    sa.Column('set_priority', sa.Enum('P1', 'P2', 'P3', 'P4', 'Q', name='project_priority'), nullable=False),
    sa.Column('hard_gates', sa.ARRAY(sa.Enum('Regulatory deadline within 6 months', 'Customer certification at risk (Coke/Pepsi)', 'Active safety non-compliance', name='hard_gate_reason')), nullable=False),
    sa.CheckConstraint('normalized_pct BETWEEN 0 AND 100', name=op.f('ck_priority_application_results_normalized_pct_range')),
    sa.ForeignKeyConstraint(['priority_application_run_id'], ['priority_application_runs.id'], name=op.f('fk_priority_application_results_priority_application_run_id_priority_application_runs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_priority_application_results_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_application_results')),
    sa.UniqueConstraint('priority_application_run_id', 'project_id', name='uq_priority_result_run_project')
    )
    op.create_table('priority_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('strategic_project', sa.Integer(), nullable=False),
    sa.Column('new_customer', sa.Integer(), nullable=False),
    sa.Column('new_options', sa.Integer(), nullable=False),
    sa.Column('regulatory_compliance', sa.Integer(), nullable=False),
    sa.Column('quality_improvements', sa.Integer(), nullable=False),
    sa.Column('rm_savings', sa.Integer(), nullable=False),
    sa.Column('total_rm_savings', sa.Integer(), nullable=False),
    sa.Column('gross_margins', sa.Integer(), nullable=False),
    sa.Column('profitability', sa.Integer(), nullable=False),
    sa.Column('annual_volume', sa.Integer(), nullable=False),
    sa.Column('three_year_volume', sa.Integer(), nullable=False),
    sa.Column('new_models', sa.Integer(), nullable=False),
    sa.Column('capex_investment', sa.Integer(), nullable=False),
    sa.Column('hard_gates', sa.ARRAY(sa.Enum('Regulatory deadline within 6 months', 'Customer certification at risk (Coke/Pepsi)', 'Active safety non-compliance', name='hard_gate_reason')), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('normalized_pct', sa.Integer(), nullable=True),
    sa.Column('suggested_band', sa.Enum('P1', 'P2', 'P3', 'P4', 'Q', name='project_priority'), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annual_volume BETWEEN 1 AND 5', name=op.f('ck_priority_scores_annual_volume_score_range')),
    sa.CheckConstraint('capex_investment BETWEEN 1 AND 5', name=op.f('ck_priority_scores_capex_investment_score_range')),
    sa.CheckConstraint('gross_margins BETWEEN 1 AND 5', name=op.f('ck_priority_scores_gross_margins_score_range')),
    sa.CheckConstraint('new_customer BETWEEN 1 AND 5', name=op.f('ck_priority_scores_new_customer_score_range')),
    sa.CheckConstraint('new_models BETWEEN 1 AND 5', name=op.f('ck_priority_scores_new_models_score_range')),
    sa.CheckConstraint('new_options BETWEEN 1 AND 5', name=op.f('ck_priority_scores_new_options_score_range')),
    sa.CheckConstraint('profitability BETWEEN 1 AND 5', name=op.f('ck_priority_scores_profitability_score_range')),
    sa.CheckConstraint('quality_improvements BETWEEN 1 AND 5', name=op.f('ck_priority_scores_quality_improvements_score_range')),
    sa.CheckConstraint('regulatory_compliance BETWEEN 1 AND 5', name=op.f('ck_priority_scores_regulatory_compliance_score_range')),
    sa.CheckConstraint('rm_savings BETWEEN 1 AND 5', name=op.f('ck_priority_scores_rm_savings_score_range')),
    sa.CheckConstraint('strategic_project BETWEEN 1 AND 5', name=op.f('ck_priority_scores_strategic_project_score_range')),
    sa.CheckConstraint('three_year_volume BETWEEN 1 AND 5', name=op.f('ck_priority_scores_three_year_volume_score_range')),
    sa.CheckConstraint('total_rm_savings BETWEEN 1 AND 5', name=op.f('ck_priority_scores_total_rm_savings_score_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_priority_scores_project_id_projects')),
    sa.ForeignKeyConstraint(['scored_by_user_id'], ['users.id'], name=op.f('fk_priority_scores_scored_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_scores')),
    sa.UniqueConstraint('project_id', name=op.f('uq_priority_scores_project_id'))
    )
    op.create_table('project_workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('step_template_id', sa.String(length=10), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('planned_start_week', sa.Integer(), nullable=True),
    sa.Column('planned_end_week', sa.Integer(), nullable=True),
    sa.Column('actual_start_week', sa.Integer(), nullable=True),
    sa.Column('actual_end_week', sa.Integer(), nullable=True),
    sa.Column('assigned_engineer_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_chamber_id', sa.Uuid(), nullable=True),
    sa.Column('eng_conflict', sa.Boolean(), nullable=False),
    sa.Column('chamber_overlap', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_chamber_id'], ['chambers.id'], name=op.f('fk_project_workflow_steps_assigned_chamber_id_chambers')),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['engineers.id'], name=op.f('fk_project_workflow_steps_assigned_engineer_id_engineers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_workflow_steps_project_id_projects')),
    sa.ForeignKeyConstraint(['step_template_id'], ['workflow_step_templates.id'], name=op.f('fk_project_workflow_steps_step_template_id_workflow_step_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_workflow_steps')),
    sa.UniqueConstraint('project_id', 'sequence_order', name='uq_project_sequence_order'),
    sa.UniqueConstraint('project_id', 'step_template_id', name='uq_project_step_template')
    )
    op.create_table('schedule_run_project_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('left_out', sa.Boolean(), nullable=False),
    sa.Column('cat_not_allowed', sa.Boolean(), nullable=False),
    sa.Column('spillover', sa.Boolean(), nullable=False),
    sa.Column('within_year', sa.Boolean(), nullable=False),
    sa.Column('last_step_end_week', sa.Integer(), nullable=True),
    sa.Column('delay_weeks_applied', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_schedule_run_project_outcomes_project_id_projects')),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], name=op.f('fk_schedule_run_project_outcomes_schedule_run_id_schedule_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_run_project_outcomes')),
    sa.UniqueConstraint('schedule_run_id', 'project_id', name='uq_run_project_outcome')
    )
    op.create_table('schedule_run_project_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('step_template_id', sa.String(length=10), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('end_week', sa.Integer(), nullable=False),
    sa.Column('assigned_engineer_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_chamber_id', sa.Uuid(), nullable=True),
    sa.Column('eng_conflict', sa.Boolean(), nullable=False),
    sa.Column('chamber_overlap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_chamber_id'], ['chambers.id'], name=op.f('fk_schedule_run_project_steps_assigned_chamber_id_chambers')),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['engineers.id'], name=op.f('fk_schedule_run_project_steps_assigned_engineer_id_engineers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_schedule_run_project_steps_project_id_projects')),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], name=op.f('fk_schedule_run_project_steps_schedule_run_id_schedule_runs')),
    sa.ForeignKeyConstraint(['step_template_id'], ['workflow_step_templates.id'], name=op.f('fk_schedule_run_project_steps_step_template_id_workflow_step_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_run_project_steps')),
    sa.UniqueConstraint('schedule_run_id', 'project_id', 'step_template_id', name='uq_run_project_step')
    )
    # ### end Alembic commands ###

    # --- Hand-written: partial unique indexes (Invariant I9) -------------
    # `WHERE is_active` (not `WHERE is_active = true`) is the idiomatic
    # Postgres partial-index predicate for a boolean column; both rows with
    # `is_active = false` are simply excluded from the index, so any number
    # of them may coexist — only a second `is_active = true` row collides.
    op.execute(
        f"CREATE UNIQUE INDEX {_SCHEDULE_RUNS_ACTIVE_IDX} "
        "ON schedule_runs (is_active) WHERE is_active"
    )
    op.execute(
        f"CREATE UNIQUE INDEX {_PRIORITY_RUNS_ACTIVE_IDX} "
        "ON priority_application_runs (is_active) WHERE is_active"
    )

    # --- Hand-written: append-only enforcement on audit_log_entries ------
    # Rejects UPDATE and DELETE unconditionally, for any role that can reach
    # this table, by raising a Postgres exception before the operation
    # applies. INSERT (the only legal write) is untouched.
    op.execute(
        f"""
        CREATE FUNCTION {_AUDIT_TRIGGER_FN}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log_entries is append-only: % is not permitted (row id=%)',
                TG_OP, COALESCE(OLD.id, NULL)
                USING ERRCODE = '23001';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_AUDIT_TRIGGER_NAME}
        BEFORE UPDATE OR DELETE ON audit_log_entries
        FOR EACH ROW EXECUTE FUNCTION {_AUDIT_TRIGGER_FN}()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # --- Hand-written additions, reversed first (autogenerate produces no
    # downgrade logic for either — both are DDL-only constructs) -----------
    op.execute(f"DROP TRIGGER IF EXISTS {_AUDIT_TRIGGER_NAME} ON audit_log_entries")
    op.execute(f"DROP FUNCTION IF EXISTS {_AUDIT_TRIGGER_FN}()")
    op.execute(f"DROP INDEX IF EXISTS {_PRIORITY_RUNS_ACTIVE_IDX}")
    op.execute(f"DROP INDEX IF EXISTS {_SCHEDULE_RUNS_ACTIVE_IDX}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_run_project_steps')
    op.drop_table('schedule_run_project_outcomes')
    op.drop_table('project_workflow_steps')
    op.drop_table('priority_scores')
    op.drop_table('priority_application_results')
    op.drop_table('projects')
    op.drop_table('user_roles')
    op.drop_table('user_hub_scopes')
    op.drop_table('schedule_runs')
    op.drop_table('priority_application_runs')
    op.drop_table('engineers')
    op.drop_table('currency_rates')
    op.drop_table('audit_log_entries')
    op.drop_table('workflow_step_templates')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('hubs')
    op.drop_table('chambers')
    # ### end Alembic commands ###

    # --- Hand-written: drop the native Postgres ENUM types ---------------
    # Alembic/SQLAlchemy quirk: `op.drop_table()` for a table with an inline
    # `sa.Enum(...)` column does NOT emit `DROP TYPE` — each `sa.Enum(...)`
    # instance is scoped to its own `op.create_table`/`op.drop_table` call,
    # not tracked across the whole migration the way `Base.metadata.drop_all()`
    # would track it. Confirmed empirically: without these, `alembic upgrade
    # head` after `alembic downgrade base` fails with `DuplicateObjectError:
    # type "lab_region" already exists` on the next `CREATE TYPE`. Must run
    # after every table that references the type has been dropped.
    for _enum_type_name in (
        "lab_region",
        "hub_name",
        "workflow_step_kind",
        "currency_code",
        "engineer_allowed_category",
        "solver_type",
        "schedule_run_status",
        "project_category",
        "project_type",
        "project_status",
        "project_priority",
        "hard_gate_reason",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum_type_name}")
