"""p9 client formulas: workflows, lead times, capacity supply, workspace, super admin

Revision ID: 5c9e1f2a7b3d
Revises: 2418c6385a72
Create Date: 2026-09-27 12:00:00.000000

P9-T01 (docs/IMPLEMENTATION_PLAN.md) — the 2026-09-27 contract revision
(ADRs 0007 lead times / step kinds / OEM workflow, 0008 capacity supply,
0009 configurable precedence, 0010 Super Admin) plus P8-T01's Project
Workspace data model, absorbed verbatim. Hand-written, not autogenerated —
this revision carries data migrations that autogenerate cannot express:

- four native enum types gain values (`project_category`, `project_status`,
  `engineer_allowed_category`, `workflow_step_kind`). Postgres refuses to
  *use* an `ALTER TYPE … ADD VALUE` label inside the transaction that added
  it, and this migration must use the new labels immediately (the OEM
  category remap, the PDD `elapsed` kinds), so every one of the four is
  recreated (rename → create → alter columns with a text cast → drop old).
  This is also what makes `downgrade()` clean: the reverse recreation only
  works after every row using a new label has been mapped back.
- `workflow_step_templates`: the 14 PDD rows keep their IDs and are renamed
  to the client's names/codes/kinds in place; the 14 OEM rows are added;
  `base_weeks` is dropped (ADR 0007 — durations come from the new
  `workflow_lead_times` table, seeded here with the 98-row table from
  docs/DOMAIN_RULES.md "Lead times"). Both seeds are embedded as literals
  so the migration is deterministic when replayed; `seed_demo_data.py`
  upserts the same rows from `domain_constants` and a test asserts the two
  agree with the DOMAIN_RULES.md table.
- OEM-hub projects are remapped to OEM categories (A+/A → A-OEM, B → B-OEM,
  C → C-OEM) and their live step rows are re-pointed from PDD-x to OEM-x
  (the OEM workflow) before the `trg_projects_category_matches_hub` trigger
  is created. A CHECK constraint on `projects` alone cannot see
  `hubs.is_oem`, hence a trigger (raising SQLSTATE 23514 / check_violation,
  which SQLAlchemy surfaces as `IntegrityError`) — see
  `models.project.category_allowed_for_hub` for the model-layer half.
- Every live `project_workflow_steps.duration_weeks` is recomputed from the
  lead-time table via the shared statement in `services.workflow_durations`
  (built on lightweight `sa.table` handles, so it does not depend on the ORM
  models' later evolution).
- Per-stage progress columns (ADR 0006) get a status derived from the
  existing `actual_*_week` pair so the new CHECK constraints hold for every
  pre-existing row.
- `project_comments` gets a BEFORE DELETE trigger (rows are soft-deleted
  only); admin scripts may bypass it for a *reset* by `SET LOCAL
  rpd.allow_comment_delete = 'on'` — never exposed through the API.
- The `Super Admin` role row is inserted (ADR 0010).

No raw SQL string interpolation: every statement below is a literal with
bound parameters or SQLAlchemy Core.
"""
from typing import Sequence, Union
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from services.workflow_durations import recompute_step_durations_statement

# revision identifiers, used by Alembic.
revision: str = '5c9e1f2a7b3d'
down_revision: Union[str, Sequence[str], None] = '2418c6385a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Embedded seeds (literal copies of domain_constants at authoring time) ----

WORKFLOWS = (
    ("PDD", "Product Development & Design (non-OEM hubs)"),
    ("OEM", "OEM workflow (OEM-HCK, OEM-Seltek)"),
)

# (workflow_id, step_id, code, name, kind, sequence_order, predecessor_ids)
STEP_TEMPLATES = (
(('PDD', 'PDD-A', 'MKTG_BRF', 'Marketing Brief', 'design', 1, ()),
('PDD', 'PDD-B', 'FEAS_STD', 'Feasibility Study (Conceptual Design)', 'design', 2, ('PDD-A',)),
('PDD', 'PDD-C', 'BUS_CASE', 'Business Case Approval', 'elapsed', 3, ('PDD-B',)),
('PDD',
'PDD-D',
'TECH_BRIEF',
'Final Technical Brief & Project Kick-off',
'design',
4,
('PDD-C',)),
('PDD', 'PDD-E', 'DESIGN', 'Design Detailing', 'design', 5, ('PDD-D',)),
('PDD', 'PDD-F', 'POC', 'Proof of Concept', 'lab', 6, ('PDD-E',)),
('PDD', 'PDD-G', 'CAPEX', 'Online CAPEX Approval', 'elapsed', 7, ('PDD-F',)),
('PDD', 'PDD-H', 'CERT', 'Certification Testing & Compliance', 'lab', 8, ('PDD-G',)),
('PDD', 'PDD-I', 'TF_1', 'TF-1', 'design', 9, ('PDD-H',)),
('PDD', 'PDD-J', 'PROD_PR', 'Pre-Production (Pr. Pr)', 'design', 10, ('PDD-I',)),
('PDD', 'PDD-K', 'TF_2', 'TF-2', 'design', 11, ('PDD-J',)),
('PDD', 'PDD-L', 'PILOT', 'Pilot', 'elapsed', 12, ('PDD-K',)),
('PDD', 'PDD-M', 'TF_3', 'TF-3', 'design', 13, ('PDD-L',)),
('PDD', 'PDD-N', 'COMM', 'Commercialization', 'elapsed', 14, ('PDD-M',)),
('OEM', 'OEM-A', 'COMM_BRF', 'Commercial Brief', 'design', 1, ()),
('OEM',
'OEM-B',
'TECH_BRIEF',
'Final Technical Brief & Project Kick-off',
'design',
2,
('OEM-A',)),
('OEM', 'OEM-C', 'BUS_CASE', 'Business Case Approval', 'elapsed', 3, ('OEM-B',)),
('OEM', 'OEM-D', 'DESIGN', 'Design Detailing', 'design', 4, ('OEM-C',)),
('OEM', 'OEM-E', 'POC', 'Proof of Concept', 'lab', 5, ('OEM-D',)),
('OEM', 'OEM-F', 'CAPEX', 'Online CAPEX Approval', 'elapsed', 6, ('OEM-E',)),
('OEM', 'OEM-G', 'TST_ANAL', 'Test Results Analysis', 'design', 7, ('OEM-F',)),
('OEM', 'OEM-H', 'CERT', 'Certification Testing & Compliance', 'lab', 8, ('OEM-G',)),
('OEM', 'OEM-I', 'TF_1', 'TF-1', 'design', 9, ('OEM-H',)),
('OEM', 'OEM-J', 'PROD_PR', 'Pre-Production (Pr. Pr)', 'design', 10, ('OEM-I',)),
('OEM', 'OEM-K', 'TF_2', 'TF-2', 'design', 11, ('OEM-J',)),
('OEM', 'OEM-L', 'PILOT', 'Pilot', 'elapsed', 12, ('OEM-K',)),
('OEM', 'OEM-M', 'TF_3', 'TF-3', 'design', 13, ('OEM-L',)),
('OEM', 'OEM-N', 'COMM', 'Commercialization', 'elapsed', 14, ('OEM-M',)))
)

# (workflow_id, category, step_id, weeks)
LEAD_TIMES = (
(('PDD', 'A+', 'PDD-A', 1),
('PDD', 'A+', 'PDD-B', 8),
('PDD', 'A+', 'PDD-C', 4),
('PDD', 'A+', 'PDD-D', 1),
('PDD', 'A+', 'PDD-E', 6),
('PDD', 'A+', 'PDD-F', 6),
('PDD', 'A+', 'PDD-G', 2),
('PDD', 'A+', 'PDD-H', 6),
('PDD', 'A+', 'PDD-I', 2),
('PDD', 'A+', 'PDD-J', 1),
('PDD', 'A+', 'PDD-K', 2),
('PDD', 'A+', 'PDD-L', 3),
('PDD', 'A+', 'PDD-M', 1),
('PDD', 'A+', 'PDD-N', 1),
('PDD', 'A', 'PDD-A', 1),
('PDD', 'A', 'PDD-B', 4),
('PDD', 'A', 'PDD-C', 4),
('PDD', 'A', 'PDD-D', 1),
('PDD', 'A', 'PDD-E', 6),
('PDD', 'A', 'PDD-F', 4),
('PDD', 'A', 'PDD-G', 2),
('PDD', 'A', 'PDD-H', 6),
('PDD', 'A', 'PDD-I', 2),
('PDD', 'A', 'PDD-J', 1),
('PDD', 'A', 'PDD-K', 2),
('PDD', 'A', 'PDD-L', 3),
('PDD', 'A', 'PDD-M', 1),
('PDD', 'A', 'PDD-N', 1),
('PDD', 'B', 'PDD-A', 1),
('PDD', 'B', 'PDD-B', 0),
('PDD', 'B', 'PDD-C', 0),
('PDD', 'B', 'PDD-D', 1),
('PDD', 'B', 'PDD-E', 4),
('PDD', 'B', 'PDD-F', 0),
('PDD', 'B', 'PDD-G', 0),
('PDD', 'B', 'PDD-H', 6),
('PDD', 'B', 'PDD-I', 0),
('PDD', 'B', 'PDD-J', 1),
('PDD', 'B', 'PDD-K', 2),
('PDD', 'B', 'PDD-L', 1),
('PDD', 'B', 'PDD-M', 1),
('PDD', 'B', 'PDD-N', 1),
('PDD', 'C', 'PDD-A', 1),
('PDD', 'C', 'PDD-B', 0),
('PDD', 'C', 'PDD-C', 0),
('PDD', 'C', 'PDD-D', 1),
('PDD', 'C', 'PDD-E', 2),
('PDD', 'C', 'PDD-F', 0),
('PDD', 'C', 'PDD-G', 0),
('PDD', 'C', 'PDD-H', 1),
('PDD', 'C', 'PDD-I', 0),
('PDD', 'C', 'PDD-J', 1),
('PDD', 'C', 'PDD-K', 1),
('PDD', 'C', 'PDD-L', 0),
('PDD', 'C', 'PDD-M', 0),
('PDD', 'C', 'PDD-N', 1),
('OEM', 'A-OEM', 'OEM-A', 1),
('OEM', 'A-OEM', 'OEM-B', 1),
('OEM', 'A-OEM', 'OEM-C', 1),
('OEM', 'A-OEM', 'OEM-D', 2),
('OEM', 'A-OEM', 'OEM-E', 2),
('OEM', 'A-OEM', 'OEM-F', 2),
('OEM', 'A-OEM', 'OEM-G', 4),
('OEM', 'A-OEM', 'OEM-H', 6),
('OEM', 'A-OEM', 'OEM-I', 0),
('OEM', 'A-OEM', 'OEM-J', 1),
('OEM', 'A-OEM', 'OEM-K', 0),
('OEM', 'A-OEM', 'OEM-L', 0),
('OEM', 'A-OEM', 'OEM-M', 0),
('OEM', 'A-OEM', 'OEM-N', 1),
('OEM', 'B-OEM', 'OEM-A', 1),
('OEM', 'B-OEM', 'OEM-B', 1),
('OEM', 'B-OEM', 'OEM-C', 1),
('OEM', 'B-OEM', 'OEM-D', 0),
('OEM', 'B-OEM', 'OEM-E', 0),
('OEM', 'B-OEM', 'OEM-F', 2),
('OEM', 'B-OEM', 'OEM-G', 2),
('OEM', 'B-OEM', 'OEM-H', 6),
('OEM', 'B-OEM', 'OEM-I', 0),
('OEM', 'B-OEM', 'OEM-J', 1),
('OEM', 'B-OEM', 'OEM-K', 0),
('OEM', 'B-OEM', 'OEM-L', 0),
('OEM', 'B-OEM', 'OEM-M', 0),
('OEM', 'B-OEM', 'OEM-N', 0),
('OEM', 'C-OEM', 'OEM-A', 0),
('OEM', 'C-OEM', 'OEM-B', 0),
('OEM', 'C-OEM', 'OEM-C', 0),
('OEM', 'C-OEM', 'OEM-D', 0),
('OEM', 'C-OEM', 'OEM-E', 0),
('OEM', 'C-OEM', 'OEM-F', 0),
('OEM', 'C-OEM', 'OEM-G', 2),
('OEM', 'C-OEM', 'OEM-H', 2),
('OEM', 'C-OEM', 'OEM-I', 0),
('OEM', 'C-OEM', 'OEM-J', 0),
('OEM', 'C-OEM', 'OEM-K', 0),
('OEM', 'C-OEM', 'OEM-L', 0),
('OEM', 'C-OEM', 'OEM-M', 0),
('OEM', 'C-OEM', 'OEM-N', 0))
)

# (hub_name, weekdays_per_week, national_holiday_days, medical_leave_days,
#  casual_leave_days, annual_leave_days)
HUB_WORK_CALENDARS = (
(('R&D-Greece', 5, 12, 0, 0, 25),
('R&D-India', 6, 13, 7, 7, 20),
('PD-India', 6, 13, 7, 7, 20),
('PD-Romania', 5, 13, 7, 0, 20),
('OEM-HCK', 6, 13, 7, 7, 20),
('OEM-Seltek', 6, 13, 7, 7, 20))
)

# Prototype-era PDD template (name, kind, base_weeks) — restored on downgrade.
LEGACY_PDD_TEMPLATES = {
    "PDD-A": ("Marketing Brief", "design", 2),
    "PDD-B": ("Concept Study", "design", 2),
    "PDD-C": ("Feasibility & Costing", "design", 2),
    "PDD-D": ("Final Tech Brief & Kick-off", "design", 1),
    "PDD-E": ("Design Detailing", "design", 4),
    "PDD-F": ("Proof of Concept", "lab", 3),
    "PDD-G": ("Design Refinement", "design", 2),
    "PDD-H": ("Certification", "lab", 4),
    "PDD-I": ("Tooling & Sourcing", "design", 3),
    "PDD-J": ("Pre-Pilot Validation", "lab", 2),
    "PDD-K": ("TF-2", "design", 2),
    "PDD-L": ("Pilot", "lab", 3),
    "PDD-M": ("Buy-off", "design", 2),
    "PDD-N": ("Commercialization", "design", 1),
}

# --- Lightweight table handles for the data migration -----------------------

t_workflows = sa.table(
    "workflows",
    sa.column("id", sa.String()),
    sa.column("name", sa.String()),
)
t_templates = sa.table(
    "workflow_step_templates",
    sa.column("id", sa.String()),
    sa.column("workflow_id", sa.String()),
    sa.column("code", sa.String()),
    sa.column("name", sa.String()),
    # Enum-typed so asyncpg binds `$n::workflow_step_kind`, not `::VARCHAR`.
    sa.column("kind", postgresql.ENUM(name="workflow_step_kind", create_type=False)),
    sa.column("sequence_order", sa.Integer()),
    sa.column("predecessor_ids", postgresql.JSONB()),
    sa.column("base_weeks", sa.Integer()),
)
t_lead_times = sa.table(
    "workflow_lead_times",
    sa.column("workflow_id", sa.String()),
    sa.column("category", postgresql.ENUM(name="project_category", create_type=False)),
    sa.column("step_id", sa.String()),
    sa.column("weeks", sa.Integer()),
)
t_hubs = sa.table(
    "hubs",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("is_oem", sa.Boolean()),
)
t_calendars = sa.table(
    "hub_work_calendars",
    sa.column("id", sa.Uuid()),
    sa.column("hub_id", sa.Uuid()),
    sa.column("weekdays_per_week", sa.Integer()),
    sa.column("national_holiday_days", sa.Numeric(5, 2)),
    sa.column("medical_leave_days", sa.Numeric(5, 2)),
    sa.column("casual_leave_days", sa.Numeric(5, 2)),
    sa.column("annual_leave_days", sa.Numeric(5, 2)),
    sa.column("weeks_in_year", sa.Integer()),
)
t_roles = sa.table(
    "roles",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("description", sa.String()),
)
t_user_roles = sa.table(
    "user_roles",
    sa.column("user_id", sa.Uuid()),
    sa.column("role_id", sa.Uuid()),
)


# --- Trigger bodies ----------------------------------------------------------

PROJECTS_CATEGORY_TRIGGER_FN = """
CREATE OR REPLACE FUNCTION rpd_projects_category_matches_hub() RETURNS trigger AS $$
DECLARE
    hub_is_oem boolean;
BEGIN
    IF NEW.category IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT is_oem INTO hub_is_oem FROM hubs WHERE id = NEW.hub_id;
    IF hub_is_oem IS NULL THEN
        RETURN NEW;  -- the FK on hub_id reports the missing hub
    END IF;
    IF hub_is_oem AND NEW.category::text NOT IN ('A-OEM', 'B-OEM', 'C-OEM') THEN
        RAISE EXCEPTION 'project on an OEM hub must carry an OEM category (A-OEM/B-OEM/C-OEM), got %',
            NEW.category
            USING ERRCODE = 'check_violation',
                  CONSTRAINT = 'ck_projects_category_matches_hub';
    END IF;
    IF NOT hub_is_oem AND NEW.category::text IN ('A-OEM', 'B-OEM', 'C-OEM') THEN
        RAISE EXCEPTION 'project on a non-OEM hub must carry A+/A/B/C, got %',
            NEW.category
            USING ERRCODE = 'check_violation',
                  CONSTRAINT = 'ck_projects_category_matches_hub';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

PROJECTS_CATEGORY_TRIGGER = """
CREATE TRIGGER trg_projects_category_matches_hub
BEFORE INSERT OR UPDATE OF category, hub_id ON projects
FOR EACH ROW EXECUTE FUNCTION rpd_projects_category_matches_hub();
"""

COMMENTS_NO_DELETE_FN = """
CREATE OR REPLACE FUNCTION rpd_project_comments_no_delete() RETURNS trigger AS $$
BEGIN
    IF current_setting('rpd.allow_comment_delete', true) = 'on' THEN
        RETURN OLD;  -- admin reset scripts only (SET LOCAL), never the API
    END IF;
    RAISE EXCEPTION 'project_comments rows are never hard-deleted; set soft_deleted_at instead'
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;
"""

COMMENTS_NO_DELETE_TRIGGER = """
CREATE TRIGGER trg_project_comments_no_delete
BEFORE DELETE ON project_comments
FOR EACH ROW EXECUTE FUNCTION rpd_project_comments_no_delete();
"""


def upgrade() -> None:
    """Upgrade schema + data."""
    bind = op.get_bind()

    # ------------------------------------------------------------------ enums
    # project_category: + A-OEM, B-OEM, C-OEM
    op.execute("ALTER TYPE project_category RENAME TO project_category_old")
    op.execute(
        "CREATE TYPE project_category AS ENUM "
        "('A+', 'A', 'B', 'C', 'A-OEM', 'B-OEM', 'C-OEM')"
    )
    op.execute(
        "ALTER TABLE projects ALTER COLUMN category TYPE project_category "
        "USING category::text::project_category"
    )
    op.execute("DROP TYPE project_category_old")

    # project_status: + Cancelled
    op.execute("ALTER TYPE project_status RENAME TO project_status_old")
    op.execute(
        "CREATE TYPE project_status AS ENUM ('In Buyoff', 'Under Industrialization', "
        "'In Development', 'In Queue', 'Commercialized', 'On Hold', 'Draft', 'Cancelled')"
    )
    op.execute(
        "ALTER TABLE projects ALTER COLUMN status TYPE project_status "
        "USING status::text::project_status"
    )
    op.execute("DROP TYPE project_status_old")

    # engineer_allowed_category: + A-OEM, B-OEM, C-OEM (array column)
    op.execute("ALTER TYPE engineer_allowed_category RENAME TO engineer_allowed_category_old")
    op.execute(
        "CREATE TYPE engineer_allowed_category AS ENUM "
        "('A+', 'A', 'B', 'C', 'OEM', 'A-OEM', 'B-OEM', 'C-OEM')"
    )
    op.execute(
        "ALTER TABLE engineers ALTER COLUMN allowed_categories "
        "TYPE engineer_allowed_category[] "
        "USING allowed_categories::text[]::engineer_allowed_category[]"
    )
    op.execute("DROP TYPE engineer_allowed_category_old")

    # workflow_step_kind: + elapsed
    op.execute("ALTER TYPE workflow_step_kind RENAME TO workflow_step_kind_old")
    op.execute("CREATE TYPE workflow_step_kind AS ENUM ('design', 'lab', 'elapsed')")
    op.execute(
        "ALTER TABLE workflow_step_templates ALTER COLUMN kind TYPE workflow_step_kind "
        "USING kind::text::workflow_step_kind"
    )
    op.execute("DROP TYPE workflow_step_kind_old")

    # -------------------------------------------------------------- workflows
    op.create_table(
        'workflows',
        sa.Column('id', sa.String(length=10), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows')),
    )
    bind.execute(
        postgresql.insert(t_workflows)
        .values([{"id": wid, "name": name} for wid, name in WORKFLOWS])
        .on_conflict_do_nothing(index_elements=["id"])
    )

    # --------------------------------------------------- workflow_step_templates
    op.add_column('workflow_step_templates', sa.Column('workflow_id', sa.String(length=10),
                                                       nullable=True))
    op.add_column('workflow_step_templates', sa.Column('code', sa.String(length=30),
                                                       nullable=True))
    op.add_column(
        'workflow_step_templates',
        sa.Column('predecessor_ids', postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
    )
    # The prototype-era single-column unique on sequence_order must go BEFORE
    # the OEM rows are inserted (OEM-A and PDD-A both have sequence_order 1);
    # its per-workflow replacement is created once workflow_id is populated.
    op.drop_constraint('uq_workflow_step_templates_sequence_order', 'workflow_step_templates',
                       type_='unique')
    # base_weeks goes away — give the upsert below a value for brand-new rows
    # first, then drop the column.
    op.alter_column('workflow_step_templates', 'base_weeks', server_default='0')

    upsert = postgresql.insert(t_templates).values(
        [
            {
                "id": step_id,
                "workflow_id": wf,
                "code": code,
                "name": name,
                "kind": kind,
                "sequence_order": seq,
                "predecessor_ids": list(preds),
                "base_weeks": 0,
            }
            for wf, step_id, code, name, kind, seq, preds in STEP_TEMPLATES
        ]
    )
    bind.execute(
        upsert.on_conflict_do_update(
            index_elements=["id"],
            set_={
                "workflow_id": upsert.excluded.workflow_id,
                "code": upsert.excluded.code,
                "name": upsert.excluded.name,
                "kind": upsert.excluded.kind,
                "sequence_order": upsert.excluded.sequence_order,
                "predecessor_ids": upsert.excluded.predecessor_ids,
            },
        )
    )

    op.alter_column('workflow_step_templates', 'workflow_id', nullable=False)
    op.alter_column('workflow_step_templates', 'code', nullable=False)
    op.alter_column('workflow_step_templates', 'predecessor_ids', server_default=None)
    op.drop_column('workflow_step_templates', 'base_weeks')
    op.create_unique_constraint('uq_workflow_step_templates_workflow_sequence',
                                'workflow_step_templates', ['workflow_id', 'sequence_order'])
    op.create_foreign_key(op.f('fk_workflow_step_templates_workflow_id_workflows'),
                          'workflow_step_templates', 'workflows', ['workflow_id'], ['id'])

    # ------------------------------------------------------- workflow_lead_times
    op.create_table(
        'workflow_lead_times',
        sa.Column('workflow_id', sa.String(length=10), nullable=False),
        sa.Column(
            'category',
            postgresql.ENUM('A+', 'A', 'B', 'C', 'A-OEM', 'B-OEM', 'C-OEM',
                            name='project_category', create_type=False),
            nullable=False,
        ),
        sa.Column('step_id', sa.String(length=10), nullable=False),
        sa.Column('weeks', sa.Integer(), nullable=False),
        sa.CheckConstraint('weeks >= 0', name=op.f('ck_workflow_lead_times_weeks_non_negative')),
        sa.ForeignKeyConstraint(['step_id'], ['workflow_step_templates.id'],
                                name=op.f('fk_workflow_lead_times_step_id_workflow_step_templates')),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'],
                                name=op.f('fk_workflow_lead_times_workflow_id_workflows')),
        sa.PrimaryKeyConstraint('workflow_id', 'category', 'step_id',
                                name=op.f('pk_workflow_lead_times')),
    )
    bind.execute(
        postgresql.insert(t_lead_times)
        .values(
            [
                {"workflow_id": wf, "category": cat, "step_id": step, "weeks": weeks}
                for wf, cat, step, weeks in LEAD_TIMES
            ]
        )
        .on_conflict_do_nothing(index_elements=["workflow_id", "category", "step_id"])
    )

    # -------------------------------------------------------- hub_work_calendars
    op.create_table(
        'hub_work_calendars',
        sa.Column('hub_id', sa.Uuid(), nullable=False),
        sa.Column('weekdays_per_week', sa.Integer(), nullable=False),
        sa.Column('national_holiday_days', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('medical_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('casual_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('annual_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('weeks_in_year', sa.Integer(), server_default='52', nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.CheckConstraint('weekdays_per_week BETWEEN 1 AND 7',
                           name=op.f('ck_hub_work_calendars_weekdays_per_week_range')),
        sa.CheckConstraint('national_holiday_days >= 0',
                           name=op.f('ck_hub_work_calendars_national_holiday_days_non_negative')),
        sa.CheckConstraint('medical_leave_days >= 0',
                           name=op.f('ck_hub_work_calendars_medical_leave_days_non_negative')),
        sa.CheckConstraint('casual_leave_days >= 0',
                           name=op.f('ck_hub_work_calendars_casual_leave_days_non_negative')),
        sa.CheckConstraint('annual_leave_days >= 0',
                           name=op.f('ck_hub_work_calendars_annual_leave_days_non_negative')),
        sa.CheckConstraint('weeks_in_year > 0',
                           name=op.f('ck_hub_work_calendars_weeks_in_year_positive')),
        sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'],
                                name=op.f('fk_hub_work_calendars_hub_id_hubs')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hub_work_calendars')),
        sa.UniqueConstraint('hub_id', name=op.f('uq_hub_work_calendars_hub_id')),
    )
    existing_hubs = {
        name: hub_id for hub_id, name in bind.execute(sa.select(t_hubs.c.id, t_hubs.c.name))
    }
    calendar_rows = [
        {
            "id": uuid.uuid4(),
            "hub_id": existing_hubs[hub_name],
            "weekdays_per_week": weekdays,
            "national_holiday_days": holidays,
            "medical_leave_days": medical,
            "casual_leave_days": casual,
            "annual_leave_days": annual,
            "weeks_in_year": 52,
        }
        for hub_name, weekdays, holidays, medical, casual, annual in HUB_WORK_CALENDARS
        if hub_name in existing_hubs
    ]
    if calendar_rows:
        bind.execute(sa.insert(t_calendars).values(calendar_rows))

    # ---------------------------------------------------------------- chambers
    op.add_column('chambers', sa.Column('maintenance_weeks', sa.Numeric(precision=5, scale=2),
                                        server_default='2', nullable=False))
    op.add_column('chambers', sa.Column('breakdown_weeks', sa.Numeric(precision=5, scale=2),
                                        server_default='0', nullable=False))
    op.add_column('chambers', sa.Column('calibration_weeks', sa.Numeric(precision=5, scale=2),
                                        server_default='1', nullable=False))
    op.create_check_constraint(op.f('ck_chambers_maintenance_weeks_non_negative'), 'chambers',
                               'maintenance_weeks >= 0')
    op.create_check_constraint(op.f('ck_chambers_breakdown_weeks_non_negative'), 'chambers',
                               'breakdown_weeks >= 0')
    op.create_check_constraint(op.f('ck_chambers_calibration_weeks_non_negative'), 'chambers',
                               'calibration_weeks >= 0')
    op.drop_column('chambers', 'weeks_per_chamber')

    # ---------------------------------------------------------------- projects
    op.add_column('projects', sa.Column('target_end_week', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('certification_testing_required', sa.Boolean(),
                                        server_default='true', nullable=False))
    op.add_column('projects', sa.Column('estimated_design_weeks',
                                        sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('projects', sa.Column('estimated_lab_weeks',
                                        sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('projects', sa.Column('schedule_stale', sa.Boolean(),
                                        server_default='false', nullable=False))
    op.create_check_constraint(op.f('ck_projects_target_end_week_positive'), 'projects',
                               'target_end_week IS NULL OR target_end_week >= 1')
    op.create_check_constraint(op.f('ck_projects_estimated_design_weeks_non_negative'),
                               'projects',
                               'estimated_design_weeks IS NULL OR estimated_design_weeks >= 0')
    op.create_check_constraint(op.f('ck_projects_estimated_lab_weeks_non_negative'), 'projects',
                               'estimated_lab_weeks IS NULL OR estimated_lab_weeks >= 0')

    # Data: OEM-hub projects carry OEM categories (A+/A -> A-OEM, B -> B-OEM,
    # C -> C-OEM), and their live step rows follow the OEM workflow.
    op.execute(
        """
        UPDATE projects AS p
        SET category = CASE p.category::text
                           WHEN 'A+' THEN 'A-OEM'::project_category
                           WHEN 'A'  THEN 'A-OEM'::project_category
                           WHEN 'B'  THEN 'B-OEM'::project_category
                           WHEN 'C'  THEN 'C-OEM'::project_category
                           ELSE p.category
                       END
        FROM hubs AS h
        WHERE h.id = p.hub_id AND h.is_oem
          AND p.category IS NOT NULL
          AND p.category::text IN ('A+', 'A', 'B', 'C')
        """
    )
    op.execute(
        """
        UPDATE project_workflow_steps AS s
        SET step_template_id = 'OEM-' || substr(s.step_template_id, 5)
        FROM projects AS p, hubs AS h
        WHERE s.project_id = p.id AND h.id = p.hub_id AND h.is_oem
          AND s.step_template_id LIKE 'PDD-%'
        """
    )
    op.execute(PROJECTS_CATEGORY_TRIGGER_FN)
    op.execute(PROJECTS_CATEGORY_TRIGGER)

    # --------------------------------------------------- project_workflow_steps
    postgresql.ENUM('Not Started', 'In Progress', 'Blocked', 'Done',
                    name='workflow_step_status').create(bind, checkfirst=True)
    op.add_column(
        'project_workflow_steps',
        sa.Column(
            'status',
            postgresql.ENUM('Not Started', 'In Progress', 'Blocked', 'Done',
                            name='workflow_step_status', create_type=False),
            server_default='Not Started', nullable=False,
        ),
    )
    op.add_column('project_workflow_steps', sa.Column('percent_complete', sa.Integer(),
                                                      server_default='0', nullable=False))
    op.add_column('project_workflow_steps', sa.Column('remaining_weeks_override', sa.Integer(),
                                                      nullable=True))
    op.add_column('project_workflow_steps', sa.Column('blocked_reason', sa.Text(),
                                                      nullable=True))

    # Data: derive a status consistent with the CHECKs from the existing
    # actual_*_week pair (the seed never populated them, but a real DB may).
    op.execute(
        """
        UPDATE project_workflow_steps
        SET status = 'Done', percent_complete = 100
        WHERE actual_start_week IS NOT NULL AND actual_end_week IS NOT NULL
          AND actual_end_week >= actual_start_week
        """
    )
    op.execute(
        """
        UPDATE project_workflow_steps
        SET status = 'In Progress'
        WHERE actual_start_week IS NOT NULL AND actual_end_week IS NULL
        """
    )
    # Inconsistent leftovers (end without start, or end < start) cannot be
    # expressed under the contract — reset them to Not Started.
    op.execute(
        """
        UPDATE project_workflow_steps
        SET actual_start_week = NULL, actual_end_week = NULL, status = 'Not Started',
            percent_complete = 0
        WHERE (actual_end_week IS NOT NULL AND actual_start_week IS NULL)
           OR (actual_end_week IS NOT NULL AND actual_start_week IS NOT NULL
               AND actual_end_week < actual_start_week)
        """
    )

    op.create_check_constraint(op.f('ck_project_workflow_steps_duration_non_negative'),
                               'project_workflow_steps', 'duration_weeks >= 0')
    op.create_check_constraint(op.f('ck_project_workflow_steps_percent_complete_range'),
                               'project_workflow_steps', 'percent_complete BETWEEN 0 AND 100')
    op.create_check_constraint(
        op.f('ck_project_workflow_steps_remaining_override_non_negative'),
        'project_workflow_steps',
        'remaining_weeks_override IS NULL OR remaining_weeks_override >= 0',
    )
    op.create_check_constraint(
        op.f('ck_project_workflow_steps_status_done_consistency'),
        'project_workflow_steps',
        "status <> 'Done' OR (percent_complete = 100 AND actual_start_week IS NOT NULL "
        "AND actual_end_week IS NOT NULL AND actual_end_week >= actual_start_week)",
    )
    op.create_check_constraint(
        op.f('ck_project_workflow_steps_status_not_started_consistency'),
        'project_workflow_steps',
        "status <> 'Not Started' OR (percent_complete = 0 AND actual_start_week IS NULL "
        "AND actual_end_week IS NULL)",
    )
    op.create_check_constraint(
        op.f('ck_project_workflow_steps_status_active_consistency'),
        'project_workflow_steps',
        "status NOT IN ('In Progress', 'Blocked') OR (actual_start_week IS NOT NULL "
        "AND actual_end_week IS NULL)",
    )
    op.create_check_constraint(
        op.f('ck_project_workflow_steps_status_blocked_reason_consistency'),
        'project_workflow_steps',
        "(status = 'Blocked' AND blocked_reason IS NOT NULL AND length(btrim(blocked_reason)) > 0) "
        "OR (status <> 'Blocked' AND blocked_reason IS NULL)",
    )

    # Data: every live duration from the lead-time table (ADR 0007).
    bind.execute(recompute_step_durations_statement())

    # ----------------------------------------------------------- schedule runs
    op.add_column('schedule_runs', sa.Column('workflow_snapshot', postgresql.JSONB(),
                                             nullable=True))
    op.add_column('schedule_run_project_steps', sa.Column('skipped', sa.Boolean(),
                                                          server_default='false',
                                                          nullable=False))
    op.add_column('schedule_run_project_outcomes', sa.Column('unconstrained_end_week',
                                                             sa.Integer(), nullable=True))
    op.add_column('schedule_run_project_outcomes', sa.Column('expected_end_week', sa.Integer(),
                                                             nullable=True))
    op.add_column('schedule_run_project_outcomes', sa.Column('projected_end_week', sa.Integer(),
                                                             nullable=True))
    op.add_column('schedule_run_project_outcomes', sa.Column('blocked', sa.Boolean(),
                                                             server_default='false',
                                                             nullable=False))
    op.add_column('schedule_run_project_outcomes', sa.Column('progress_pct', sa.Integer(),
                                                             nullable=True))
    op.add_column('schedule_run_project_outcomes', sa.Column('data_error', sa.Text(),
                                                             nullable=True))

    # ------------------------------------------------- project_files / comments
    op.create_table(
        'project_files',
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column(
            'category',
            sa.Enum('Drawing', 'Test Report', 'Certification', 'Costing', 'Supplier Doc',
                    'Photo', 'Other', name='project_file_category'),
            nullable=False,
        ),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
        sa.Column('size_bytes', sa.BigInteger(), nullable=False),
        sa.Column('content_type', sa.String(length=255), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('minio_object_key', sa.String(length=1024), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_project_files_size_non_negative')),
        sa.CheckConstraint('version >= 1', name=op.f('ck_project_files_version_positive')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'],
                                name=op.f('fk_project_files_project_id_projects')),
        sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'],
                                name=op.f('fk_project_files_uploaded_by_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_project_files')),
        sa.UniqueConstraint('minio_object_key', name=op.f('uq_project_files_minio_object_key')),
        sa.UniqueConstraint('project_id', 'display_name', 'version',
                            name='uq_project_files_name_version'),
    )
    op.create_table(
        'project_comments',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('body_md', sa.Text(), nullable=False),
        sa.Column('author_user_id', sa.Uuid(), nullable=False),
        sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('soft_deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('mentioned_user_ids', postgresql.JSONB(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['author_user_id'], ['users.id'],
                                name=op.f('fk_project_comments_author_user_id_users')),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'],
                                name=op.f('fk_project_comments_project_id_projects')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_project_comments')),
    )
    op.execute(COMMENTS_NO_DELETE_FN)
    op.execute(COMMENTS_NO_DELETE_TRIGGER)

    # ------------------------------------------------------------ Super Admin
    bind.execute(
        postgresql.insert(t_roles)
        .values(
            [
                {
                    "id": uuid.uuid4(),
                    "name": "Super Admin",
                    "description": "Every right on every surface; sole manager of admin "
                                   "roles and Workflow Settings (ADR 0010).",
                }
            ]
        )
        .on_conflict_do_nothing(index_elements=["name"])
    )


def downgrade() -> None:
    """Downgrade schema + data (lossy by nature: OEM categories/steps and the
    Cancelled status have no pre-P9 representation and are mapped back to the
    closest legacy value; schedule-run step rows that reference OEM-x steps
    are deleted because the OEM template rows they point at go away)."""
    bind = op.get_bind()

    # ------------------------------------------------------------ Super Admin
    super_admin_id = bind.execute(
        sa.select(t_roles.c.id).where(t_roles.c.name == "Super Admin")
    ).scalar_one_or_none()
    if super_admin_id is not None:
        bind.execute(sa.delete(t_user_roles).where(t_user_roles.c.role_id == super_admin_id))
        bind.execute(sa.delete(t_roles).where(t_roles.c.id == super_admin_id))

    # ------------------------------------------------- project_files / comments
    op.execute("DROP TRIGGER IF EXISTS trg_project_comments_no_delete ON project_comments")
    op.execute("DROP FUNCTION IF EXISTS rpd_project_comments_no_delete()")
    op.drop_table('project_comments')
    op.drop_table('project_files')
    op.execute("DROP TYPE IF EXISTS project_file_category")

    # ----------------------------------------------------------- schedule runs
    op.drop_column('schedule_run_project_outcomes', 'data_error')
    op.drop_column('schedule_run_project_outcomes', 'progress_pct')
    op.drop_column('schedule_run_project_outcomes', 'blocked')
    op.drop_column('schedule_run_project_outcomes', 'projected_end_week')
    op.drop_column('schedule_run_project_outcomes', 'expected_end_week')
    op.drop_column('schedule_run_project_outcomes', 'unconstrained_end_week')
    op.drop_column('schedule_run_project_steps', 'skipped')
    op.drop_column('schedule_runs', 'workflow_snapshot')

    # --------------------------------------------------- project_workflow_steps
    for name in (
        'ck_project_workflow_steps_status_blocked_reason_consistency',
        'ck_project_workflow_steps_status_active_consistency',
        'ck_project_workflow_steps_status_not_started_consistency',
        'ck_project_workflow_steps_status_done_consistency',
        'ck_project_workflow_steps_remaining_override_non_negative',
        'ck_project_workflow_steps_percent_complete_range',
        'ck_project_workflow_steps_duration_non_negative',
    ):
        op.drop_constraint(op.f(name), 'project_workflow_steps', type_='check')
    op.drop_column('project_workflow_steps', 'blocked_reason')
    op.drop_column('project_workflow_steps', 'remaining_weeks_override')
    op.drop_column('project_workflow_steps', 'percent_complete')
    op.drop_column('project_workflow_steps', 'status')
    op.execute("DROP TYPE IF EXISTS workflow_step_status")

    # Live OEM-x step rows back to PDD-x; historical run rows on OEM-x dropped.
    op.execute(
        """
        UPDATE project_workflow_steps
        SET step_template_id = 'PDD-' || substr(step_template_id, 5)
        WHERE step_template_id LIKE 'OEM-%'
        """
    )
    op.execute("DELETE FROM schedule_run_project_steps WHERE step_template_id LIKE 'OEM-%'")
    op.execute(
        """
        UPDATE chambers
        SET allowed_stages = array_remove(array_remove(allowed_stages, 'OEM-E'), 'OEM-H')
        """
    )

    # ---------------------------------------------------------------- projects
    op.execute("DROP TRIGGER IF EXISTS trg_projects_category_matches_hub ON projects")
    op.execute("DROP FUNCTION IF EXISTS rpd_projects_category_matches_hub()")
    op.execute(
        """
        UPDATE projects
        SET category = CASE category::text
                           WHEN 'A-OEM' THEN 'A'::project_category
                           WHEN 'B-OEM' THEN 'B'::project_category
                           WHEN 'C-OEM' THEN 'C'::project_category
                           ELSE category
                       END
        WHERE category::text IN ('A-OEM', 'B-OEM', 'C-OEM')
        """
    )
    op.execute("UPDATE projects SET status = 'On Hold' WHERE status::text = 'Cancelled'")
    op.drop_constraint(op.f('ck_projects_estimated_lab_weeks_non_negative'), 'projects', type_='check')
    op.drop_constraint(op.f('ck_projects_estimated_design_weeks_non_negative'), 'projects',
                       type_='check')
    op.drop_constraint(op.f('ck_projects_target_end_week_positive'), 'projects', type_='check')
    op.drop_column('projects', 'schedule_stale')
    op.drop_column('projects', 'estimated_lab_weeks')
    op.drop_column('projects', 'estimated_design_weeks')
    op.drop_column('projects', 'certification_testing_required')
    op.drop_column('projects', 'target_end_week')

    # ---------------------------------------------------------------- chambers
    op.add_column('chambers', sa.Column('weeks_per_chamber', sa.Numeric(precision=6, scale=2),
                                        server_default='0', nullable=False))
    op.drop_constraint(op.f('ck_chambers_calibration_weeks_non_negative'), 'chambers', type_='check')
    op.drop_constraint(op.f('ck_chambers_breakdown_weeks_non_negative'), 'chambers', type_='check')
    op.drop_constraint(op.f('ck_chambers_maintenance_weeks_non_negative'), 'chambers', type_='check')
    op.drop_column('chambers', 'calibration_weeks')
    op.drop_column('chambers', 'breakdown_weeks')
    op.drop_column('chambers', 'maintenance_weeks')

    # -------------------------------------------------------- hub_work_calendars
    op.drop_table('hub_work_calendars')

    # ------------------------------------------------------- workflow_lead_times
    op.drop_table('workflow_lead_times')

    # --------------------------------------------------- workflow_step_templates
    bind.execute(sa.delete(t_templates).where(t_templates.c.workflow_id == "OEM"))
    op.add_column('workflow_step_templates', sa.Column('base_weeks', sa.Integer(),
                                                       server_default='0', nullable=False))
    for step_id, (name, kind, base_weeks) in LEGACY_PDD_TEMPLATES.items():
        bind.execute(
            sa.update(t_templates)
            .where(t_templates.c.id == step_id)
            .values(name=name, kind=kind, base_weeks=base_weeks)
        )
    op.alter_column('workflow_step_templates', 'base_weeks', server_default=None)
    op.drop_constraint(op.f('fk_workflow_step_templates_workflow_id_workflows'),
                       'workflow_step_templates', type_='foreignkey')
    op.drop_constraint('uq_workflow_step_templates_workflow_sequence', 'workflow_step_templates',
                       type_='unique')
    op.create_unique_constraint('uq_workflow_step_templates_sequence_order',
                                'workflow_step_templates', ['sequence_order'])
    op.drop_column('workflow_step_templates', 'predecessor_ids')
    op.drop_column('workflow_step_templates', 'code')
    op.drop_column('workflow_step_templates', 'workflow_id')

    # -------------------------------------------------------------- workflows
    op.drop_table('workflows')

    # ------------------------------------------------------------------ enums
    op.execute("ALTER TYPE workflow_step_kind RENAME TO workflow_step_kind_new")
    op.execute("CREATE TYPE workflow_step_kind AS ENUM ('design', 'lab')")
    op.execute(
        "ALTER TABLE workflow_step_templates ALTER COLUMN kind TYPE workflow_step_kind "
        "USING kind::text::workflow_step_kind"
    )
    op.execute("DROP TYPE workflow_step_kind_new")

    op.execute(
        """
        UPDATE engineers
        SET allowed_categories = array_remove(array_remove(array_remove(
            allowed_categories, 'A-OEM'::engineer_allowed_category),
            'B-OEM'::engineer_allowed_category), 'C-OEM'::engineer_allowed_category)
        """
    )
    op.execute("ALTER TYPE engineer_allowed_category RENAME TO engineer_allowed_category_new")
    op.execute(
        "CREATE TYPE engineer_allowed_category AS ENUM ('A+', 'A', 'B', 'C', 'OEM')"
    )
    op.execute(
        "ALTER TABLE engineers ALTER COLUMN allowed_categories "
        "TYPE engineer_allowed_category[] "
        "USING allowed_categories::text[]::engineer_allowed_category[]"
    )
    op.execute("DROP TYPE engineer_allowed_category_new")

    op.execute("ALTER TYPE project_status RENAME TO project_status_new")
    op.execute(
        "CREATE TYPE project_status AS ENUM ('In Buyoff', 'Under Industrialization', "
        "'In Development', 'In Queue', 'Commercialized', 'On Hold', 'Draft')"
    )
    op.execute(
        "ALTER TABLE projects ALTER COLUMN status TYPE project_status "
        "USING status::text::project_status"
    )
    op.execute("DROP TYPE project_status_new")

    op.execute("ALTER TYPE project_category RENAME TO project_category_new")
    op.execute("CREATE TYPE project_category AS ENUM ('A+', 'A', 'B', 'C')")
    op.execute(
        "ALTER TABLE projects ALTER COLUMN category TYPE project_category "
        "USING category::text::project_category"
    )
    op.execute("DROP TYPE project_category_new")
