"""Declarative base and shared mixins for all SQLAlchemy 2.0 async models.

`Base.metadata` is the single target Alembic (P1-T02) points `env.py` at:

    from models import Base
    target_metadata = Base.metadata

Every model module in this package must import `Base` from here rather than
declaring its own `DeclarativeBase` subclass, so a single `MetaData` collects
every table.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so autogenerated Alembic migrations produce stable,
# predictable constraint/index names instead of dialect-default ones that churn
# across SQLAlchemy versions.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Python-side UUID4 default (not `gen_random_uuid()`/pgcrypto) so primary
    keys are generated portably without requiring a Postgres extension — see
    docs/MEMORY.md P1-T01 entry for the rationale.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """`created_at` / `updated_at`, both server-side so they're correct even for
    rows written outside the ORM (e.g. a future bulk-load script) and consistent
    with DB server time rather than app-server clock skew.
    """

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
